export const Users = [
    {
        id : 1,
        firstname : "Lilian",
        lastname : "Sartore",
        homecountry: "Italy",
        homecity: "Rome",
        countryflag: "/Italy.png",
        university: "University of Michigan",
        major: "Mathematics",
        details: "Hello, my name is Lilian, I enjoy mentoring fellow international students. A fun fact about myself, I have been to 23 different countries. I'm currently working on a Masters in Mathematics and I have lived in the United States for the last 3 years. When I'm not studying for exams, I am the president of the Italian language club on campus.",
        image: "/Lilian.jpg"
    },
    {
        "id": 2,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 3,
        "firstname": "Eteri",
        "lastname": "Giorgadze",
        "homecountry": "Georgia",
        "countryflag": "/Georgia.png",
        "homecity": "Tbilisi",
        "university": "Villanova University",
        "major": "Biology",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 4,
        "firstname": "Qiu",
        "lastname": "Song",
        "homecountry": "China",
        "countryflag": "/China.png",
        "homecity": "Chengdu",
        "university": "University of Virginia",
        "major": "Chemistry",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 5,
        "firstname": "Arthur",
        "lastname": "Jacobs",
        "homecountry": "Belgium",
        "countryflag": "/Belgium.png",
        "homecity": "Brussels",
        "university": "University of Nebraska",
        "major": "Chemistry",
        "details": "To be added",
        "image": "/testprofile.jpg"
    },
    {
        "id": 6,
        "firstname": "Qiu",
        "lastname": "Song",
        "homecountry": "China",
        "countryflag": "/China.png",
        "homecity": "Chengdu",
        "university": "University of Virginia",
        "major": "Chemistry",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 7,
        "firstname": "Qiu",
        "lastname": "Song",
        "homecountry": "China",
        "countryflag": "/China.png",
        "homecity": "Chengdu",
        "university": "University of Virginia",
        "major": "Chemistry",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 8,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 9,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 10,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 11,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 12,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 13,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 14,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 15,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 16,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 17,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 18,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 19,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 20,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 21,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 22,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 23,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 24,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 25,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },
    {
        "id": 26,
        "firstname": "Nilam",
        "lastname": "Gajos",
        "homecountry": "India",
        "countryflag": "/India.png",
        "homecity": "Agra",
        "university": "Carnegie Mellon University",
        "major": "Computer Science",
        "details": "To be added",
        "image": "/question.png"
    },

]