export const Users = [
 {
    "id": 2,
    "firstname": "Elena",
    "lastname": "Ricci",
    "homecountry": "Italy",
    "homecity": "Milan",
    "countryflag": "/Italy.png",
    "university": "Stanford University",
    "major": "Computer Science",
    "details": "Hi, I'm Elena. I have a passion for coding and artificial intelligence. Originally from Milan, Italy, I now pursue my dreams at Stanford University, majoring in Computer Science. I love exploring new technologies and contributing to open-source projects in my free time.",
    "image": "/question.png"
  },
  {
    "id": 3,
    "firstname": "Miguel",
    "lastname": "Lopez",
    "homecountry": "Spain",
    "homecity": "Barcelona",
    "countryflag": "/Spain.png",
    "university": "Harvard University",
    "major": "Economics",
    "details": "Hola! I'm Miguel from Barcelona, Spain. Currently, I'm a student at Harvard University majoring in Economics. I enjoy discussing economic policies and their impact on global markets. In my free time, you can find me exploring the cultural scene of Boston or playing football with friends.",
    "image": "/question.png"
  },
  {
    "id": 4,
    "firstname": "Yuki",
    "lastname": "Tanaka",
    "homecountry": "Japan",
    "homecity": "Tokyo",
    "countryflag": "/Japan.png",
    "university": "Georgetown University",
    "major": "Electrical Engineering",
    "details": "Konnichiwa! I'm Yuki from Tokyo, Japan. Currently pursuing a degree in Electrical Engineering at Georgetown, I'm fascinated by the intersection of technology and society. When not in the lab, I enjoy traditional Japanese tea ceremonies and exploring the vibrant tech scene in Washington D.C. .",
    "image": "/question.png"
  },
  {
    "id": 5,
    "firstname": "Olga",
    "lastname": "Ivanova",
    "homecountry": "Russia",
    "homecity": "Moscow",
    "countryflag": "/Russia.png",
    "university": "Columbia University",
    "major": "Political Science",
    "details": "Privet! I'm Olga, originally from Moscow, Russia. Studying Political Science at Columbia University, I'm passionate about international relations and diplomacy. In my free time, I enjoy exploring the diverse neighborhoods of New York City and trying out different cuisines.",
    "image": "/question.png"
  },
  {
    "id": 8,
    "firstname": "Chen",
    "lastname": "Wei",
    "homecountry": "China",
    "homecity": "Shanghai",
    "countryflag": "/China.png",
    "university": "Princeton University",
    "major": "Physics",
    "details": "你好! I'm Chen Wei from Shanghai, China. Currently, I'm delving into the fascinating world of Physics at Princeton University. Whether it's conducting experiments in the lab or engaging in philosophical discussions about the universe, I find joy in unraveling the mysteries of the cosmos.",
    "image": "/question.png"
  },
  {
    "id": 9,
    "firstname": "Sophie",
    "lastname": "Dubois",
    "homecountry": "France",
    "homecity": "Paris",
    "countryflag": "/France.png",
    "university": "University of Chicago",
    "major": "Art History",
    "details": "Bonjour! I'm Sophie from the City of Lights, Paris. Studying Art History at the University of Chicago, I'm captivated by the evolution of artistic expression throughout history. Whether it's visiting museums or participating in campus art exhibitions, I find inspiration in the vibrant arts community.",
    "image": "/question.png"
  },
  {
    "id": 10,
    "firstname": "Raj",
    "lastname": "Patel",
    "homecountry": "India",
    "homecity": "Mumbai",
    "countryflag": "/India.png",
    "university": "University of Nebraska",
    "major": "Computer Science",
    "details": "Namaste! I'm Raj from Mumbai, India. Pursuing a degree in Computer Science at Nebraska, I'm passionate about innovation and technology. From coding projects to exploring the tech scene in Boston, I strive to contribute to advancements that positively impact society.",
    "image": "/question.png"
  },
    {
    "id": 12,
    "firstname": "Irina",
    "lastname": "Popescu",
    "homecountry": "Romania",
    "homecity": "Timisoara",
    "countryflag": "/Romania.png",
    "university": "Harvard University",
    "major": "Biomedical Engineering",
    "details": "Buna! I'm Irina from Timisoara, Romania. Currently pursuing Biomedical Engineering at Harvard University, I'm passionate about merging technology and healthcare. In my free time, I engage in medical outreach programs and explore the historical charm of Cambridge.",
    "image": "/question.png"
  },
  {
    "id": 13,
    "firstname": "Giorgio",
    "lastname": "Ricci",
    "homecountry": "Italy",
    "homecity": "Naples",
    "countryflag": "/Italy.png",
    "university": "Ohio State University",
    "major": "Aerospace Engineering",
    "details": "Ciao! I'm Giorgio from Naples, Italy. Delving into the world of Aerospace Engineering at Ohio State, I'm passionate about pushing the boundaries of flight. In my free time, I enjoy model aircraft design and exploring Ohio State's cutting-edge labs.",
    "image": "/question.png"
  },
  {
    "id": 14,
    "firstname": "Elise",
    "lastname": "Dubois",
    "homecountry": "France",
    "homecity": "Lyon",
    "countryflag": "/France.png",
    "university": "Stanford University",
    "major": "Computer Science",
    "details": "Bonjour! I'm Elise from Lyon, France. Navigating the world of Computer Science at Stanford University, I'm passionate about algorithms and artificial intelligence. In my free time, I explore the Silicon Valley tech scene and engage in hackathons.",
    "image": "/question.png"
  },
  {
    "id": 15,
    "firstname": "Carlos",
    "lastname": "Santos",
    "homecountry": "Portugal",
    "homecity": "Lisbon",
    "countryflag": "/Portugal.png",
    "university": "University of California, Berkeley",
    "major": "Environmental Science",
    "details": "Olá! I'm Carlos from Lisbon, Portugal. Currently studying Environmental Science at UC Berkeley, I'm dedicated to understanding and addressing environmental challenges. In my free time, I explore the natural beauty of the Bay Area and participate in ecological restoration projects.",
    "image": "/question.png"
  },
  {
    "id": 16,
    "firstname": "Katerina",
    "lastname": "Papadopoulos",
    "homecountry": "Greece",
    "homecity": "Athens",
    "countryflag": "/Greece.png",
    "university": "University of Chicago",
    "major": "Physics",
    "details": "Χαίρετε! I'm Katerina from Athens, Greece. Immersed in the world of Physics at the University of Chicago, I'm passionate about unraveling the mysteries of the cosmos. In my free time, I engage in theoretical physics discussions and explore the unique scientific culture at the University of Chicago.",
    "image": "/question.png"
  },
  {
    "id": 17,
    "firstname": "Viktor",
    "lastname": "Andersson",
    "homecountry": "Sweden",
    "homecity": "Stockholm",
    "countryflag": "/Sweden.png",
    "university": "University of Chicago",
    "major": "Economics",
    "details": "Hej! I'm Viktor from Stockholm, Sweden. Exploring the complexities of Economics at the University of Chicago, I'm passionate about economic theory and policy. In my free time, I attend economic forums and enjoy the vibrant cultural scene in Chicago.",
    "image": "/question.png"
  },
  {
    "id": 18,
    "firstname": "Eva",
    "lastname": "Hernandez",
    "homecountry": "Spain",
    "homecity": "Barcelona",
    "countryflag": "/Spain.png",
    "university": "Princeton University",
    "major": "Chemistry",
    "details": "¡Hola! I'm Eva from Barcelona, Spain. Delving into the world of Chemistry at Princeton University, I'm passionate about molecular structures and chemical reactions. In my free time, I explore the historic charm of Princeton and conduct experiments in the lab.",
    "image": "/question.png"
  },
  {
    "id": 19,
    "firstname": "Lucas",
    "lastname": "Moreau",
    "homecountry": "France",
    "homecity": "Marseille",
    "countryflag": "/France.png",
    "university": "University of Pennsylvania",
    "major": "Finance",
    "details": "Salut! I'm Lucas from Marseille, France. Navigating the world of Finance at the University of Pennsylvania, I'm passionate about investment strategies and financial markets. In my free time, I explore the historic streets of Philadelphia and attend finance seminars.",
    "image": "/question.png"
  },
  {
    "id": 20,
    "firstname": "Lara",
    "lastname": "Schmidt",
    "homecountry": "Germany",
    "homecity": "Hamburg",
    "countryflag": "/Germany.png",
    "university": "Columbia University",
    "major": "Art History",
    "details": "Hallo! I'm Lara from Hamburg, Germany. Immersed in the world of Art History at Columbia University, I'm passionate about the evolution of artistic expression. In my free time, I explore the art galleries of New York City and engage in creative discussions.",
    "image": "/question.png"
  },
  {
    "id": 21,
    "firstname": "Matej",
    "lastname": "Novak",
    "homecountry": "Slovakia",
    "homecity": "Bratislava",
    "countryflag": "/Slovakia.png",
    "university": "Yale University",
    "major": "Political Science",
    "details": "Ahoj! I'm Matej from Bratislava, Slovakia. Delving into the complexities of Political Science at Yale University, I'm passionate about global politics and diplomatic relations. In my free time, I engage in political discussions and explore the historical charm of New Haven.",
    "image": "/question.png"
  },
  {
    "id": 22,
    "firstname": "Elena",
    "lastname": "Vargas",
    "homecountry": "Spain",
    "homecity": "Valencia",
    "countryflag": "/Spain.png",
    "university": "University of Georgia",
    "major": "Computer Science",
    "details": "Hola! I'm Elena from Valencia, Spain. Diving into the world of Computer Science at the University of Georgia, I'm passionate about coding and software development. In my free time, I cheer for the Bulldogs at football games and explore the southern charm of Athens.",
    "image": "/question.png"
  },
  {
    "id": 23,
    "firstname": "Antonio",
    "lastname": "Moreno",
    "homecountry": "Argentina",
    "homecity": "Rosario",
    "countryflag": "/Argentina.png",
    "university": "University of South Carolina",
    "major": "Marketing",
    "details": "Hola! I'm Antonio from Rosario, Argentina. Navigating the world of Marketing at the University of South Carolina, I'm passionate about brand strategies and consumer behavior. In my free time, I cheer for the Gamecocks at football games and explore the historic charm of Columbia.",
    "image": "/question.png"
  },
  {
    "id": 24,
    "firstname": "Isabel",
    "lastname": "Silva",
    "homecountry": "Portugal",
    "homecity": "Lisbon",
    "countryflag": "/Portugal.png",
    "university": "University of Kentucky",
    "major": "Political Science",
    "details": "Olá! I'm Isabel from Lisbon, Portugal. Delving into the complexities of Political Science at the University of Kentucky, I'm passionate about international relations and diplomacy. In my free time, I attend Wildcat football games and explore the cultural scene of Lexington.",
    "image": "/question.png"
  },
  {
    "id": 25,
    "firstname": "Diego",
    "lastname": "Gomez",
    "homecountry": "Colombia",
    "homecity": "Bogotá",
    "countryflag": "/Colombia.png",
    "university": "University of Florida",
    "major": "Business Administration",
    "details": "Hola! I'm Diego from Bogotá, Colombia. Pursuing a degree in Business Administration at the University of Florida, I'm passionate about entrepreneurship and global business strategies. In my free time, I enjoy Gator football games and explore the vibrant culture of Gainesville.",
    "image": "/question.png"
  },
  {
    "id": 26,
    "firstname": "Rosa",
    "lastname": "Navarro",
    "homecountry": "Spain",
    "homecity": "Barcelona",
    "countryflag": "/Spain.png",
    "university": "University of Tennessee",
    "major": "Chemistry",
    "details": "¡Hola! I'm Rosa from Barcelona, Spain. Immersed in the world of Chemistry at the University of Tennessee, I'm passionate about molecular structures and chemical reactions. In my free time, I attend Volunteer football games and conduct experiments in the lab.",
    "image": "/question.png"
  },
  {
    "id": 27,
    "firstname": "Lucas",
    "lastname": "Fernandez",
    "homecountry": "Argentina",
    "homecity": "Buenos Aires",
    "countryflag": "/Argentina.png",
    "university": "University of Missouri",
    "major": "Journalism",
    "details": "Hola! I'm Lucas from Buenos Aires, Argentina. Currently studying Journalism at the University of Missouri, I'm passionate about storytelling and media production. In my free time, I attend Mizzou football games and explore the vibrant culture of Columbia.",
    "image": "/question.png"
  },
  {
    "id": 28,
    "firstname": "Maria",
    "lastname": "Almeida",
    "homecountry": "Brazil",
    "homecity": "Sao Paulo",
    "countryflag": "/Brazil.png",
    "university": "University of Mississippi",
    "major": "International Business",
    "details": "Oi! I'm Maria from Sao Paulo, Brazil. Navigating the world of International Business at the University of Mississippi, I'm passionate about global trade and cultural exchange. In my free time, I cheer for the Rebels at football games and explore the southern charm of Oxford.",
    "image": "/question.png"
  },
  {
    "id": 30,
    "firstname": "Ana",
    "lastname": "Rodriguez",
    "homecountry": "Spain",
    "homecity": "Madrid",
    "countryflag": "/Spain.png",
    "university": "Auburn University",
    "major": "Biomedical Sciences",
    "details": "Hola! I'm Ana from Madrid, Spain. Immersed in the world of Biomedical Sciences at Auburn University, I'm passionate about medical research and healthcare innovation. In my free time, I shout War Eagle at Auburn football games and engage in campus health initiatives.",
    "image": "/question.png"
  },
  {
    "id": 32,
    "firstname": "Camila",
    "lastname": "Santos",
    "homecountry": "Brazil",
    "homecity": "Rio de Janeiro",
    "countryflag": "/Brazil.png",
    "university": "Oklahoma State University",
    "major": "Agricultural Economics",
    "details": "Oi! I'm Camila from Rio de Janeiro, Brazil. Currently studying Agricultural Economics at Oklahoma State University, I'm passionate about sustainable farming practices. In my free time, I attend Cowboys football games and explore the agricultural landscapes of Stillwater.",
    "image": "/question.png"
  },
  {
    "id": 34,
    "firstname": "Sofia",
    "lastname": "Silva",
    "homecountry": "Argentina",
    "homecity": "Buenos Aires",
    "countryflag": "/Argentina.png",
    "university": "Texas Tech University",
    "major": "Architecture",
    "details": "Hola! I'm Sofia from Buenos Aires, Argentina. Pursuing Architecture at Texas Tech University, I'm passionate about innovative design and sustainable urban planning. In my free time, I attend Red Raiders football games and sketch architectural concepts.",
    "image": "/question.png"
  },
  {
    "id": 36,
    "firstname": "Lucia",
    "lastname": "Rodriguez",
    "homecountry": "Spain",
    "homecity": "Barcelona",
    "countryflag": "/Spain.png",
    "university": "Iowa State University",
    "major": "Environmental Science",
    "details": "¡Hola! I'm Lucia from Barcelona, Spain. Currently exploring Environmental Science at Iowa State University, I'm dedicated to understanding and addressing environmental challenges. In my free time, I attend Cyclones football games and participate in ecological initiatives.",
    "image": "/question.png"
  },
  {
    "id": 39,
    "firstname": "Daniel",
    "lastname": "Herrera",
    "homecountry": "Colombia",
    "homecity": "Bogotá",
    "countryflag": "/Colombia.png",
    "university": "Texas Christian University",
    "major": "Finance",
    "details": "¡Hola! I'm Daniel from Bogotá, Colombia. Navigating the world of Finance at TCU, I'm passionate about investment strategies and financial markets. In my free time, I attend Horned Frogs football games and explore the dynamic city of Fort Worth.",
    "image": "/question.png"
  },
  {
    "id": 40,
    "firstname": "Eva",
    "lastname": "Ortega",
    "homecountry": "Spain",
    "homecity": "Seville",
    "countryflag": "/Spain.png",
    "university": "University of Kansas",
    "major": "Biomedical Sciences",
    "details": "¡Hola! I'm Eva from Seville, Spain. Delving into the world of Biomedical Sciences at the University of Kansas, I'm passionate about medical research and healthcare innovation. In my free time, I attend Jayhawks football games and engage in campus health initiatives.",
    "image": "/question.png"
  },
       {
    "id": 41,
    "firstname": "Hiroshi",
    "lastname": "Tanaka",
    "homecountry": "Japan",
    "homecity": "Tokyo",
    "countryflag": "/Japan.png",
    "university": "University of Maryland",
    "major": "Electrical Engineering",
    "details": "Hello, I'm Hiroshi from Tokyo, Japan. Pursuing a degree in Electrical Engineering at the University of Maryland, I'm passionate about innovative technologies. In my free time, I explore the tech community in College Park and enjoy the cultural diversity on campus.",
    "image": "/question.png"
  },
  {
    "id": 42,
    "firstname": "Ananya",
    "lastname": "Singh",
    "homecountry": "India",
    "homecity": "New Delhi",
    "countryflag": "/India.png",
    "university": "Georgia Institute of Technology",
    "major": "Computer Science",
    "details": "Greetings! I'm Ananya from New Delhi, India. Navigating the world of Computer Science at Georgia Tech, I'm passionate about algorithms and artificial intelligence. In my free time, I contribute to coding projects and explore the vibrant tech scene in Atlanta.",
    "image": "/question.png"
  },
  {
    "id": 43,
    "firstname": "Cheng",
    "lastname": "Li",
    "homecountry": "China",
    "homecity": "Shanghai",
    "countryflag": "/China.png",
    "university": "Virginia Tech",
    "major": "Mechanical Engineering",
    "details": "Greetings! I'm Cheng from Shanghai, China. Pursuing Mechanical Engineering at Virginia Tech, I'm passionate about robotics and sustainable design. In my free time, I engage in engineering projects and explore the scenic beauty of Blacksburg.",
    "image": "/question.png"
  },
  {
    "id": 44,
    "firstname": "Lina",
    "lastname": "Abdullah",
    "homecountry": "Saudi Arabia",
    "homecity": "Riyadh",
    "countryflag": "/Saudi_Arabia.png",
    "university": "University of Florida",
    "major": "Business Administration",
    "details": "Hello, I'm Lina from Riyadh, Saudi Arabia. Delving into the world of Business Administration at the University of Florida, I'm passionate about entrepreneurship and global business strategies. In my free time, I enjoy Gator football games and explore the vibrant culture of Gainesville.",
    "image": "/question.png"
  },
  {
    "id": 45,
    "firstname": "Abdul",
    "lastname": "Malik",
    "homecountry": "Pakistan",
    "homecity": "Islamabad",
    "countryflag": "/Pakistan.png",
    "university": "North Carolina State University",
    "major": "Biomedical Engineering",
    "details": "Hello, I'm Abdul from Islamabad, Pakistan. Immersed in the world of Biomedical Engineering at NC State, I'm passionate about medical research and healthcare innovation. In my free time, I engage in campus health initiatives and explore the research opportunities in Raleigh.",
    "image": "/question.png"
  },
  {
    "id": 46,
    "firstname": "Yuki",
    "lastname": "Kobayashi",
    "homecountry": "Japan",
    "homecity": "Osaka",
    "countryflag": "/Japan.png",
    "university": "Florida State University",
    "major": "Psychology",
    "details": "Hello, I'm Yuki from Osaka, Japan. Currently exploring Psychology at Florida State, I'm passionate about understanding the human mind. In my free time, I participate in psychology research and enjoy the lively atmosphere in Tallahassee.",
    "image": "/question.png"
  },
  {
    "id": 47,
    "firstname": "Aisha",
    "lastname": "Al-Farsi",
    "homecountry": "Oman",
    "homecity": "Muscat",
    "countryflag": "/Oman.png",
    "university": "Texas A&M University",
    "major": "Chemical Engineering",
    "details": "Hello, I'm Aisha from Muscat, Oman. Diving into the world of Chemical Engineering at Texas A&M, I'm passionate about sustainable processes. In my free time, I engage in engineering projects and embrace the Aggie spirit in College Station.",
    "image": "/question.png"
  },
  {
    "id": 48,
    "firstname": "Seung-Hoon",
    "lastname": "Kim",
    "homecountry": "South Korea",
    "homecity": "Seoul",
    "countryflag": "/South_Korea.png",
    "university": "University of South Carolina",
    "major": "International Business",
    "details": "Hello, I'm Seung-Hoon from Seoul, South Korea. Delving into the world of International Business at the University of South Carolina, I'm passionate about global trade and cultural exchange. In my free time, I attend Gamecocks football games and explore the vibrant city of Columbia.",
    "image": "/question.png"
  },
  {
    "id": 49,
    "firstname": "Priya",
    "lastname": "Patel",
    "homecountry": "India",
    "homecity": "Mumbai",
    "countryflag": "/India.png",
    "university": "Clemson University",
    "major": "Computer Engineering",
    "details": "Greetings! I'm Priya from Mumbai, India. Pursuing Computer Engineering at Clemson University, I'm passionate about hardware design and software development. In my free time, I contribute to coding projects and enjoy the Clemson Tiger spirit at football games.",
    "image": "/question.png"
  },
]
